### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by chirchir12**
-We have completed our New York Times Clone Project using Semantic HTML5.
 -We used all floats, flexbox and grid to create the layout of the site
-the site is not responsive yet

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @chirchir12 & @misterpaul4  :wave:
-
-
**Friendly reminder:**  You should activate linter in this project.
- Please take a step back and fix that and make sure linter is working as is required and that all checks are passing successfully.
- This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, you have done a great job 👍 , However, there are a few issues we have to address before we move ahead. Kindly find comments below:
* Let us fix the image in this section
cnt. Let us re-size and center it
* Let us re-factor our CSS file. We did some refactoring but we could do more. Let us apply the DRY rule.
* Let us fix the footer section. The following images show our version and that of the original, let us compare and fix the changes
```Currently```
cntf
```Original```
cntf2
* Kindly add your emails to the author section of the README file and add detailed descript to the README

Kindly make these changes and submit another code review 🙂 
Happy coding _ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by uryelah** [comment]
Hello **Chirchir ChirChir** & **Paul Ajuizeogu**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Great job fixing the required changes from the last review!🌟**

You guys did an amazing job with the clone lettering, nice attention to details for the colors and font-size. The page looks really nice.

There are some minor issues on your code that need to be solved before moving forwards so hang in there! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [x] Make sure there are no warnings or errors on the [HTML validator.](https://validator.w3.org/nu/)

- [x] Make sure the images and their titles have enough margin between them:
Screenshot_2020-04-06 New York Times Clone

- [x] Even with the fixed footer, make sure the last row of the normal footer is visible like in the 
original site:
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(6)
Note how you can't see the '© 2020 The New York Times Company' line in your clone:
Screenshot_2020-04-06 New York Times Clone(1)


-----

- [x] [OPTIONAL] Add some hover interactions for the links and buttons on the page. Check how their color and text-decoration change when hovering them with your mouse on the [original page.](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👏

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS TEAM 👏👏👏

Your project looks awesome🎉🎉
This project meets the requirements for approval.

**STATUS: APPROVED ✅**

- [ ] - However, kindly remove the inline-comment in your CSS file.👍

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
